project:
  type: website
  output-dir: docs

website:
  title: "Francisca Hernández"
  navbar:
    right:
      - href: index.qmd
        text: Sobre mí
      - href: proyects.qmd
        text: Proyectos
      - href: contacto.qmd
        text: Contacto
      - text: Materiales
        menu:
          - href: materiales/ayudantia-prueba/ayudantia-aadd-ii-prueba.qmd
            text: Ayudantía Prueba
          - href: materiales/web-scraping/webscraping-en-r.qmd
            text: Hacer WebScraping en R

format:
  html:
    theme: cosmo
    css: style.css
    toc: false