project:
  type: website
  output-dir: docs

website:
  title: "Francisca Hernández"
  navbar:
    right:
      - href: index.qmd
        text: Sobre mí
      - href: proyects.qmd
        text: Proyectos
      - href: contacto.qmd
        text: Contacto
      - href: materiales/ayudantia-aadd-ii-prueba.qmd
        text: Ayudantías
format:
  html:
    theme: cosmo
    toc: false
